const menuItems = [
    {
        name: "Crispy Samosa (2 pcs)",
        description: "Golden fried pastry filled with spiced potato and green peas, served with mint & tamarind chutney.",
        price: 30,
        category: "Snacks",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=80",
        isAvailable: true,
        stockQuantity: 40,
        preparationTimeMinutes: 3,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Classic Cheese Veg Burger",
        description: "Crispy vegetable patty topped with melted cheese, lettuce, tomatoes, and mayo in a toasted sesame bun.",
        price: 70,
        category: "Fast Food",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80",
        isAvailable: true,
        stockQuantity: 25,
        preparationTimeMinutes: 7,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Paneer Tikka Roll",
        description: "Char-grilled marinated paneer cubes rolled in a soft paratha with sliced onions and mint sauce.",
        price: 90,
        category: "Fast Food",
        image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&q=80",
        isAvailable: true,
        stockQuantity: 20,
        preparationTimeMinutes: 8,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Masala Butter Dosa",
        description: "Crispy fermented rice crepe filled with spicy potato mash, served with sambar and coconut chutney.",
        price: 80,
        category: "South Indian",
        image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&q=80",
        isAvailable: true,
        stockQuantity: 30,
        preparationTimeMinutes: 6,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Steamed Idli Sambar (3 pcs)",
        description: "Soft and fluffy steamed rice cakes served with hot lentil sambar and fresh coconut chutney.",
        price: 50,
        category: "South Indian",
        image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&q=80",
        isAvailable: true,
        stockQuantity: 35,
        preparationTimeMinutes: 4,
        isVeg: true,
        isPopular: false,
    },
    {
        name: "Special Canteen Maggi",
        description: "Classic 2-minute noodles tossed with butter, finely chopped onions, tomatoes, and extra masala.",
        price: 45,
        category: "Snacks",
        image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&q=80",
        isAvailable: true,
        stockQuantity: 50,
        preparationTimeMinutes: 5,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Veg Fried Rice & Manchurian",
        description: "Wok-tossed aromatic basmati rice with veggies paired with savory vegetable Manchurian gravy.",
        price: 110,
        category: "Meals",
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&q=80",
        isAvailable: true,
        stockQuantity: 20,
        preparationTimeMinutes: 10,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Chole Bhature (2 pcs)",
        description: "Fluffy deep-fried leavened sourdough bread served with spicy chickpea curry and pickled onions.",
        price: 100,
        category: "Meals",
        image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&q=80",
        isAvailable: true,
        stockQuantity: 25,
        preparationTimeMinutes: 8,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Thick Cold Coffee",
        description: "Chilled blended coffee made with rich milk, ice cream, and chocolate syrup drizzle.",
        price: 60,
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&q=80",
        isAvailable: true,
        stockQuantity: 40,
        preparationTimeMinutes: 3,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Masala Chai",
        description: "Freshly brewed hot milk tea infused with cardamom, ginger, and aromatic Indian spices.",
        price: 20,
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80",
        isAvailable: true,
        stockQuantity: 100,
        preparationTimeMinutes: 2,
        isVeg: true,
        isPopular: true,
    },
    {
        name: "Fresh Sweet Lime (Mosambi) Juice",
        description: "Freshly squeezed sweet lime juice with a pinch of black salt.",
        price: 50,
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&q=80",
        isAvailable: true,
        stockQuantity: 30,
        preparationTimeMinutes: 4,
        isVeg: true,
        isPopular: false,
    },
    {
        name: "Chocolate Brownie with Ice Cream",
        description: "Warm fudge brownie topped with a scoop of vanilla ice cream and warm hot fudge.",
        price: 80,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1579954115545-a95591f28be0?w=500&q=80",
        isAvailable: true,
        stockQuantity: 15,
        preparationTimeMinutes: 3,
        isVeg: true,
        isPopular: false,
    }
];

module.exports = menuItems;
